#!/usr/bin/env python3
"""
Generate the data-driven figures for the GeoAI-for-Africa survey straight from
the curated extraction spreadsheet, so the numbers in the figures cannot drift
away from the numbers in the data.

    python3 figures/build_figures.py

Reads   figures/source/Reviewed_articles_only.xlsx
Writes  figures/fig-yearly.tex
        figures/fig-domain.tex
        figures/fig-methods.tex
        figures/fig-models-year.tex
        figures/fig-journals.tex
        figures/fig-spatiotemporal.tex
        figures/fig-resolution.tex
        figures/generated/numbers.tex     (LaTeX macros for use in the prose)
        figures/generated/NUMBERS.md      (every derived number + paper comparison)

The generated .tex files are plain TikZ/pgfplots with no external dependencies,
so they compile on Overleaf unchanged. Re-run this locally after any
spreadsheet edit and re-upload the generated files.

NOT generated (no source column exists for these):
  fig-prisma.tex   - screening counts; awaiting confirmation of the split
  fig-imagery.tex  - panels (b) imagery access and (c) sensor/scale strategy
"""
import collections
import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.exit("pip install openpyxl")

HERE = Path(__file__).resolve().parent
SRC = HERE / "source" / "Reviewed_articles_only.xlsx"
GEN = HERE / "generated"
GEN.mkdir(exist_ok=True)

BANNER = ("%% GENERATED by figures/build_figures.py from\n"
          "%%   figures/source/Reviewed_articles_only.xlsx\n"
          "%% Do not edit by hand: edit the spreadsheet and re-run the script.\n")

# ---------------------------------------------------------------- load
# Primary source is the wide "Studies" sheet: one row per study, multi-valued
# cells delimited by ";" (Country by ","). Sensor, model and platform
# classifications live in source/lookups.json so they can be read and edited.
# Three things exist only in the previous extraction, old_Reviewed_articles_only
# .xlsx, and are joined on title: the spectral-index rows, the weather rows and
# the single / multiple / sub-regional / continental coding of each study.
import json
OLD = HERE / "source" / "old_Reviewed_articles_only.xlsx"
LK = json.loads((HERE / "source" / "lookups.json").read_text())
wb = openpyxl.load_workbook(SRC, data_only=True)
wbo = openpyxl.load_workbook(OLD, data_only=True)


def sheet(name, book=None):
    ws = (book or wb)[name]
    hdr = [str(c).strip() if c is not None else "" for c in
           next(ws.iter_rows(min_row=1, max_row=1, values_only=True))]
    return [dict(zip(hdr, r)) for r in ws.iter_rows(min_row=2, values_only=True)
            if any(v is not None for v in r)]


def split(v, seps=";"):
    if v in (None, ""):
        return []
    return [x.strip() for x in re.split("[" + seps + "]", str(v)) if x.strip()]


def normt(t):
    return re.sub(r"[^a-z0-9]", "", str(t).lower())[:60]


def blank(v):
    return v is None or str(v).strip() in ("", "-", "NA", "N/A", "None", "none")


STUDIES = sheet("Studies")
N = len(STUDIES)
for _i, _r in enumerate(STUDIES, 1):
    _r["study_id"] = _i
title2id = {normt(r["Title"]): r["study_id"] for r in STUDIES}

# ---- the old file, keyed to the new study_id by title
_osa = {normt(r["AA_Title"]): r for r in sheet("Selected_articles", wbo)}
_missing = [r["Title"] for r in STUDIES if normt(r["Title"]) not in _osa]
if _missing:
    sys.exit("no old-file row for: %s" % _missing)
_oid2t = {}
for _nm in ("methods_long", "eo_long"):
    for _r in sheet(_nm, wbo):
        _oid2t.setdefault(int(_r["study_id"]), normt(_r["AA_Title"]))


def old2new(old_id):
    t = _oid2t.get(int(old_id))
    if t is None or t not in title2id:
        sys.exit("old study_id %s has no title match in the new file" % old_id)
    return title2id[t]


# SA: the per-study columns the figures use
SA = []
for r in STUDIES:
    o = _osa[normt(r["Title"])]
    SA.append({"study_id": r["study_id"], "Year": r["Year"], "Domain": r["Domain"],
               "Journal": r["Journal"], "Spatio-temporal": r.get("Spatio-temporal"),
               "Multi-countries": o.get("Multi-countries"),
               "Repository": r.get("Repository"), "Data link": r.get("Data link"),
               "Interactive platform": r.get("Interactive platform")})

_unknown = []
# ML: one row per (study, model), classified by the lookup
ML = []
for r in STUDIES:
    for m in split(r["Models / algorithms"]):
        if m in LK["skip_models"]:
            continue
        if m not in LK["methods"]:
            _unknown.append("model: " + m); continue
        fam, cat = LK["methods"][m]
        ML.append({"study_id": r["study_id"], "Year": r["Year"], "Method": m,
                   "Family": fam, "Category": cat})
# EO: one row per (study, sensor)
EO = []
for r in STUDIES:
    for sn in split(r["EO sensors"]):
        if sn not in LK["sensors"]:
            _unknown.append("sensor: " + sn); continue
        cat, plat, res = LK["sensors"][sn]
        EO.append({"study_id": r["study_id"], "Year": r["Year"], "Sensor": sn,
                   "Category": cat, "Platform": plat, "Resolution": res})
# PL: one row per (study, canonical platform)
PL = []
for r in STUDIES:
    _seen = set()
    for pt in split(r["Computing platform"], ";,"):
        if pt not in LK["platforms"]:
            _unknown.append("platform: " + pt); continue
        c = LK["platforms"][pt]
        if c not in _seen:
            _seen.add(c); PL.append({"study_id": r["study_id"], "Platform": c})
# CO: one row per (study, named country); regional labels are not countries
REGIONAL = {"Africa", "Sub-Saharan Africa"}
# one cell reads "Malawi and Madagascar", so " and " is treated as a delimiter too


def countries(v):
    return [c.strip() for c in re.split(r",| and ", str(v or "")) if c.strip() and c.strip() not in REGIONAL]


CO = [{"study_id": r["study_id"], "Country": c} for r in STUDIES for c in countries(r["Country"])]
# JL: studies per venue
_jc = collections.Counter(str(r.get("Journal") or "").strip() for r in STUDIES)
JL = [{"Journal": j, "studies": n} for j, n in _jc.items() if j]
# WL: weather sources, from the new column through the canonicalisation map
def _wtoks(v):
    out = []
    for x in re.split(r"[;,/]", str(v)):
        x = re.sub(r"^\s*Weather\s+[Pp]roducts?\s*\(\s*", "", x).strip(" )")   # wrapper may follow a ";"
        if x:
            out.append(x)
    return out


def _wkey(tok):
    import unicodedata
    t = unicodedata.normalize("NFKD", tok).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]", "", t.lower())[:40]


WL = []
for r in STUDIES:
    if blank(r.get("Weather data source")):
        continue
    seen = set()
    for tok in _wtoks(r["Weather data source"]):
        k = _wkey(tok)
        hit = next((v for kk, v in LK["weather"].items() if k.startswith(kk) or kk.startswith(k)), None)
        if hit is None:
            _unknown.append("weather: " + tok); continue
        if hit and hit not in seen:
            seen.add(hit); WL.append({"study_id": r["study_id"], "Source": hit})
# DM: DEM sources, one row per (study, source)
DM = [{"study_id": r["study_id"], "Source": d}
      for r in STUDIES for d in split(r.get("DEM / terrain source"), ";,")]
if _unknown:
    sys.exit("add these to source/lookups.json: %s" % sorted(set(_unknown)))
# IX: spectral indices, from the old file until Ian confirms the EO features column
IX = [{"study_id": old2new(_r["study_id"]), "Index": _r["Index"], "Family": _r.get("Family")}
      for _r in sheet("indices_long", wbo)]


# ---------------------------------------------------------------- taxonomy fix
# "Neural network" (ANN 8, MLP 7, Neural Network 5) and "Deep neural network"
# (DNN 6) are separated only by which term the original authors used, not by any
# reported difference in depth. They also straddle the Classical/Deep boundary on
# that basis alone. Merged here into one feedforward family; renamed so it does
# not read as a superset of the CNN families, which are themselves deep networks.
FAMILY_MERGE = {
    "Neural network": "Feedforward network",
    "Deep neural network": "Feedforward network",
}
FAMILY_CATEGORY_OVERRIDE = {"Feedforward network": "Deep Learning"}
for _r in ML:                      # apply the family merge in place
    _f = str(_r.get("Family") or "").strip()
    if _f in FAMILY_MERGE:
        _r["Family"] = FAMILY_MERGE[_f]
        _r["Category"] = FAMILY_CATEGORY_OVERRIDE[FAMILY_MERGE[_f]]


def txt(row, key):
    v = row.get(key)
    return str(v).strip() if v not in (None, "") else ""


def by(rows, key):
    """Distinct study_id per value of `key`."""
    d = collections.defaultdict(set)
    for r in rows:
        d[txt(r, key)].add(r["study_id"])
    return d


def esc(s):
    return s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


_DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
           "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def macroname(s):
    """LaTeX control sequences may only contain letters."""
    out = []
    for ch in s:
        if ch.isdigit():
            out.append(_DIGITS[ch])
        elif ch.isalpha():
            out.append(ch)
    return "".join(out)


def symkey(s):
    """A symbolic-coordinate key pgfplots can parse: no parens, commas, braces."""
    k = re.sub(r"[^A-Za-z0-9 \-]", "", s).strip()
    return re.sub(r"\s+", " ", k)


SHORT = {
    "Random forest": "Random forest and variants",
    "Feedforward network": "Feedforward (ANN/MLP/DNN)",   # tick label only; "networks" costs 1.3 cm of an 8.37 cm column
    "Self-supervised and representation learning": "Self-supervised",
    "Semi-supervised segmentation": "Semi-supervised",
    "CNN - classification": "CNN, classification",
    "CNN - segmentation": "CNN, segmentation",
    "CNN - detection": "CNN, detection",
}


def wrap(csv, indent="    ", width=88):
    """Break a comma-separated list over several lines using %-continuations,
    so no line runs to 900 characters and a diff stays readable."""
    # split on top-level commas only: a label such as {CNN, detection} holds one
    # of its own, and breaking the line there let the %-continuation eat the space
    parts, depth, cur = [], 0, ""
    for ch in csv:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur); cur = ""
        else:
            cur += ch
    parts.append(cur)
    out, line = [], ""
    for part in parts:
        cand = (line + "," + part) if line else part
        if len(cand) > width and line:
            out.append(line + ",%")
            line = part
        else:
            line = cand
    out.append(line)
    return ("\n" + indent).join(out)


def axislabels(items):
    """items: list of (display, value) low->high. Returns (symbolic, ticklabels, coords)."""
    keys = [symkey(d) for d, _ in items]
    disp = [esc(SHORT.get(d, d)).replace("<", "$<$").replace(">", "$>$")
            for d, _ in items]
    return (",".join(keys),
            ",".join("{%s}" % d for d in disp),
            " ".join("(%d,%s)" % (v, k) for (_, v), k in zip(items, keys)))


notes = []          # lines for NUMBERS.md
macros = {}         # name -> value for numbers.tex

# ================================================================ 1. YEAR
years = collections.Counter(txt(r, "Year") for r in SA)
yk = sorted(years)
coords = " ".join(f"({y},{years[y]})" for y in yk)
(HERE / "fig-yearly.tex").write_text(BANNER + r"""
\begin{figure}[pos=!t]   %% cas-dc reads the option as key=value; a bare [!t] leaves the float with no allowed position
\centering
\begin{tikzpicture}
\begin{axis}[
  jsybar,
  width=\columnwidth, height=5.2cm,
  xlabel={Year}, ylabel={Publications},
  symbolic x coords={%s},
  xtick=data,
  x tick label style={font=\scriptsize},
  ymin=0, ymax=%d, ytick={0,10,20,30},
  nodes near coords,
  every node near coord/.append style={yshift=1pt},
  bar width=10pt,
]
\addplot[draw=none, fill=jsBlue] coordinates {%s};
\end{axis}
\end{tikzpicture}
\caption{Publications per year across the %d reviewed studies, %s to %s.
The %s count covers January to 20 May only, when the search closed.}
\label{fig:yearly_studies}
\end{figure}
""" % (",".join(yk), max(years.values()) + 5, coords, N, yk[0], yk[-1], yk[-1]))
notes.append(("Publications per year",
              ", ".join(f"{y}={years[y]}" for y in yk) + f" (sum {sum(years.values())})",
              "PNG had 2024=25, 2025=32, 2026=15"))
macros["nStudies"] = N
for y in yk:
    macros[f"nYear{y}"] = years[y]

# ================================================================ 2. DOMAIN (pie)
dom = collections.Counter(txt(r, "Domain") for r in SA)
order = [d for d, _ in dom.most_common()]
PIECOL = ["jsBlue", "jsTeal", "jsAmber", "jsGreen", "jsPlum", "jsRust", "jsGrey"]
wedges, inpct, outlbl = [], [], []
ang = 90.0
for i, d in enumerate(order):
    c = dom[d]
    sweep = c / N * 360.0
    a0, a1 = ang, ang - sweep
    mid = (a0 + a1) / 2.0
    col = PIECOL[i % len(PIECOL)]
    wedges.append(r"  \filldraw[slice, fill=%s] (0,0) -- (%.2f:\R) arc (%.2f:%.2f:\R) -- cycle;"
                  % (col, a0, a0, a1))
    pct = c / N * 100
    m = mid % 360
    anchor = ("west" if m < 70 or m > 290 else
              "south" if 70 <= m <= 110 else
              "east" if 110 < m < 250 else "north")
    # One journal column is 8.37 cm, so labels beside the pie are stacked: the
    # name breaks at "&" (or its first space) and the count sits underneath.
    name = esc(d)
    if anchor in ("west", "east"):
        name = (name.replace(" \\& ", " \\&\\\\", 1) if " \\& " in name
                else name.replace(" ", "\\\\", 1))
    if sweep >= 40:                      # room for the percentage inside the wedge
        inpct.append(r"  \node[inpct] at (%.2f:0.62*\R) {%.1f\%%};" % (mid, pct))
        lab = "%s\\\\\\textcolor{jsAxis}{(n = %d)}" % (name, c)
    else:
        lab = "%s %.1f\\%%\\\\\\textcolor{jsAxis}{(n = %d)}" % (name, pct, c)
    align = {"west": "left", "east": "right"}.get(anchor, "center")
    outlbl.append(r"  \draw[lead] (%.2f:\R) -- (%.2f:\L);" % (mid, mid))
    outlbl.append(r"  \node[outlbl, anchor=%s, align=%s] at (%.2f:\L) {%s};" % (anchor, align, mid, lab))
    ang = a1
    macros["nDom" + re.sub(r"[^A-Za-z]", "", d)] = c

(HERE / "fig-domain.tex").write_text(BANNER + r"""
\begin{figure}[pos=!t]
\centering
\begin{tikzpicture}
  \def\R{1.8}
  \def\L{2.08}
  \tikzset{
    slice/.style={draw=white, line width=1.2pt},
    inpct/.style={font=\footnotesize, text=white},
    outlbl/.style={font=\footnotesize, inner sep=2pt},
    lead/.style={draw=jsAxis, line width=0.4pt},
  }
%s

%s

%s
\end{tikzpicture}
\caption{Distribution of the %d reviewed studies across the five application domains.}
\label{fig:domain}
\end{figure}
""" % ("\n".join(wedges), "\n".join(inpct), "\n".join(outlbl), N))
notes.append(("Application domains",
              "; ".join(f"{d} {dom[d]} ({dom[d]/N*100:.1f}%)" for d in order),
              "matches the paper"))

# ================================================================ 3. METHODS (family level)
cat_studies = by(ML, "Category")
n_cls = len(cat_studies.get("Classical ML", set()))
n_dl = len(cat_studies.get("Deep Learning", set()))
macros["nClassical"], macros["nDeep"] = n_cls, n_dl

fam = collections.defaultdict(set)
famcat = {}
for r in ML:
    f, c = txt(r, "Family"), txt(r, "Category")
    fam[f].add(r["study_id"])
    famcat[f] = c

# families named individually in the prose, so the counts cannot drift
for _f, _k in (("SVM", "nSVM"), ("Decision tree", "nDecisionTree")):
    if _f in fam:
        macros[_k] = len(fam[_f])
# Random Forest the algorithm is a Method; the "Random forest" family also holds
# Extra Trees and Canonical Correlation Forest. Prose that names the algorithm
# uses nRandomForest; the family bar in the figure shows nRandomForestFamily.
_meth = collections.defaultdict(set)
for r in ML:
    _meth[txt(r, "Method")].add(r["study_id"])
macros["nRandomForest"] = len(_meth.get("Random Forest", set()))
macros["nRandomForestFamily"] = len(fam.get("Random forest", set()))
_variants = sorted({txt(r, "Method") for r in ML
                    if txt(r, "Family") == "Random forest" and txt(r, "Method") != "Random Forest"})
notes.append(("Random Forest",
              f"algorithm {macros['nRandomForest']}; family {macros['nRandomForestFamily']} "
              f"(adds {', '.join(_variants)})", ""))


def panel(cat, den):
    items = sorted(((f, len(s)) for f, s in fam.items() if famcat[f] == cat),
                   key=lambda x: x[1])
    syms, ticks, crd = axislabels(items)
    return items, syms, ticks, crd, max(n for _, n in items)


cls_items, cls_sym, cls_ticks, cls_crd, cls_max = panel("Classical ML", n_cls)
dl_items, dl_sym, dl_ticks, dl_crd, dl_max = panel("Deep Learning", n_dl)

(HERE / "fig-methods-split.tex").write_text(BANNER + r"""%% Plotted at FAMILY level, which is how the taxonomy in methods_long is
%% structured. This collapses the ANN / Neural Network / MLP synonyms into one
%% "Neural network" family and groups the CNN variants by what they do.
%% Note the taxonomy places shallow neural nets under Classical ML and only
%% DNNs under Deep Learning.
\begin{figure}[pos=htbp]
\centering
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 1, horizontal sep=38mm},
  height=6.4cm,
]
\nextgroupplot[
  jsxbar, bar width=8pt,
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
  width=0.42\linewidth,
  title={(a) Classical machine learning\\[-1pt]{\footnotesize\mdseries n = %d studies}},
  title style={align=center, at={(0.5,1)}, anchor=south, yshift=3pt},
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,20,40,60,80},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
]
\addplot[draw=none, fill=jsAmber] coordinates {%s};

\nextgroupplot[
  jsxbar, bar width=8pt,
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
  width=0.42\linewidth,
  title={(b) Deep learning\\[-1pt]{\footnotesize\mdseries n = %d studies}},
  title style={align=center, at={(0.5,1)}, anchor=south, yshift=3pt},
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,5,10,15,20},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
]
\addplot[draw=none, fill=jsBlue] coordinates {%s};
\end{groupplot}
\end{tikzpicture}
\caption{Method families across the reviewed corpus, counted as distinct studies.
(a) The %d studies applying a classical model. (b) The %d studies applying a deep
model. Fifteen studies apply both and so appear in both panels; within a panel a
study is counted once per family.}
\label{fig:methods-split}
\end{figure}
""" % (n_cls, cls_max + 12, cls_sym, cls_ticks, cls_crd,
       n_dl, dl_max + 4, dl_sym, dl_ticks, dl_crd, n_cls, n_dl))
notes.append(("Method denominators", f"classical n={n_cls}, deep n={n_dl}",
              "paper implies 102 and 63"))
notes.append(("Classical families",
              "; ".join(f"{f} {n}" for f, n in reversed(cls_items)), ""))
notes.append(("Deep families",
              "; ".join(f"{f} {n}" for f, n in reversed(dl_items)), ""))


# ---------------- families ranked, coloured by learning paradigm ----------
PARADIGM = {
    "Random forest": "Supervised", "SVM": "Supervised",
    "Gradient boosting": "Supervised", "Decision tree": "Supervised",
    "k-NN": "Supervised", "Linear & probabilistic": "Supervised",
    "Feedforward network": "Supervised",
    "CNN - classification": "Supervised", "CNN - segmentation": "Supervised",
    "CNN - detection": "Supervised", "Recurrent": "Supervised",
    "Spatio-temporal": "Supervised", "Transformer": "Supervised",
    "Clustering": "Unsupervised",
    "Self-supervised and representation learning": "Self-supervised",
    "Semi-supervised segmentation": "Semi-supervised",
    "Foundation model": "Foundation / pretrained",
}
# Colour carries one signal only: supervised or not. Naming each non-supervised
# paradigm in a legend would be redundant, since each contains exactly one family
# and the family name already says which paradigm it is.
PCOL = {"Supervised": "jsBlue", "Self-supervised": "jsAmber",
        "Unsupervised": "jsAmber", "Semi-supervised": "jsAmber",
        "Foundation / pretrained": "jsAmber"}

unmapped = [f for f in fam if f not in PARADIGM]
if unmapped:
    sys.exit("family with no paradigm mapping: %s" % unmapped)

allfam = sorted(((f, len(v)) for f, v in fam.items()), key=lambda x: x[1])
fsym, fticks, _ = axislabels(allfam)

# exclusive paradigm assignment: a specialised paradigm outranks supervised
par = collections.defaultdict(set)
for r in ML:
    par[PARADIGM[txt(r, "Family")]].add(r["study_id"])
PREC = ["Foundation / pretrained", "Semi-supervised", "Self-supervised",
        "Unsupervised", "Supervised"]
assign = {}
for p in PREC:
    for sid in par[p]:
        assign.setdefault(sid, p)
excl = collections.Counter(assign.values())
macros["nSupervisedOnly"] = excl["Supervised"]
# Exclusive assignment, so the four non-supervised counts below sum exactly to
# nNonSupervised and no study is double-counted. nMethodsRecorded is smaller
# than nStudies when a study records no method at all.
macros["nMethodsRecorded"] = len(assign)
macros["nNonSupervised"] = len(assign) - excl["Supervised"]
for _p, _k in (("Self-supervised", "nSelfSupervised"),
               ("Unsupervised", "nClustering"),
               ("Foundation / pretrained", "nFoundationModel"),
               ("Semi-supervised", "nSemiSupervised")):
    macros[_k] = excl[_p]

series = []
for col in ("jsBlue", "jsAmber"):
    pts = [(f, n) for f, n in allfam if PCOL[PARADIGM[f]] == col]
    if not pts:
        continue
    crd = " ".join("(%d,%s)" % (n, symkey(f)) for f, n in pts)
    if len(crd) > 80:
        crd = "\n    " + crd.replace(") (", ")\n    (") + "\n  "
    series.append(r"\addplot[draw=none, fill=%s, bar shift=0pt] coordinates {%s};"
                  % (col, crd))

(HERE / "fig-methods.tex").write_text(BANNER + r"""%%%% Method families ranked by study count, coloured by the learning paradigm
%%%% each family belongs to. This avoids the classical/deep boundary, which the
%%%% paper's Section 3.1 deliberately does not draw, and matches the section's
%%%% own organising principle.
\begin{figure}[pos=htbp]
\centering
\begin{tikzpicture}
\begin{axis}[
  jsxbar, bar width=9pt,
  scale only axis, width=3.9cm, height=%0.1fcm,   %%%% plot area; labels keep native size in the 8.37 cm column
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,20,40,60,80},
  symbolic y coords={%s},
  ytick={%s},
  yticklabels={%s},
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
]
%s
\end{axis}
\end{tikzpicture}
\caption{Method families across the %d reviewed studies, ranked by the number of
studies applying each. A study using more than one family is counted once per
family, so the bars sum to more than %d. The random forest bar also holds Extra
Trees and Canonical Correlation Forest. Amber marks the four families that fall
outside the supervised paradigm: clustering (unsupervised), self-supervised
representation learning, semi-supervised segmentation, and foundation models.
Counting each study once, under the most specialised paradigm it uses, %d studies
(%.1f\%%) are purely supervised.}
\label{fig:methods}
\end{figure}
""" % (0.46 * len(allfam) + 0.3, max(n for _, n in allfam) + 14,
       wrap(fsym), wrap(fsym), wrap(fticks),
       "\n".join(series), N, N, excl["Supervised"], excl["Supervised"] / N * 100))

notes.append(("Learning paradigm, exclusive assignment",
              "; ".join("%s %d (%.1f%%)" % (p, excl[p], excl[p] / N * 100)
                        for p in PREC[::-1] if excl[p]),
              "paper says supervised 91.3%% - MATCHES exactly"))

# ================================================================ 4. MODEL FAMILY x YEAR
CATS = [("Classical ML", "jsAmber"), ("Deep Learning", "jsBlue"),
        ("Foundation model", "jsTeal")]
seen = collections.defaultdict(set)
for r in ML:
    seen[(txt(r, "Category"), txt(r, "Year"))].add(r["study_id"])
tot_year = {y: sum(len(seen[(c, y)]) for c, _ in CATS) for y in yk}
plots = []
for c, col in CATS:
    crd = " ".join(f"({y},{len(seen[(c,y)])})" for y in yk)
    plots.append(r"\addplot[draw=none, fill=%s] coordinates {%s};" % (col, crd)
                 + "\n\\addlegendentry{%s}" % c)
(HERE / "fig-models-year.tex").write_text(BANNER + r"""%% Bars count STUDIES per category per year. A study using both a classical and
%% a deep model contributes to both series, so bars sum to more than the corpus.
\begin{figure}[pos=!t]
\centering
\begin{tikzpicture}
\begin{axis}[
  jsybarstack,
  width=\columnwidth, height=5.6cm,
  x tick label style={font=\scriptsize},   %%%% eleven 4-digit years must fit one column under cas-dc
  xlabel={Year}, ylabel={Studies},
  symbolic x coords={%s}, xtick=data,
  ymin=0, ymax=%d,
  bar width=10pt,
  legend style={at={(0.02,0.98)}, anchor=north west, legend columns=1, font=\footnotesize},
]
%s
\end{axis}
\end{tikzpicture}
\caption{Model categories used per year. A study applying both a classical and a
deep model contributes to both series. The %s bar covers January to 20 May only.}
\label{fig:years_n_models}
\end{figure}
""" % (",".join(yk), max(tot_year.values()) + 6, "\n".join(plots), yk[-1]))
notes.append(("Model category by year",
              "; ".join(f"{y}: " + "/".join(str(len(seen[(c,y)])) for c, _ in CATS)
                        for y in yk),
              "order: classical/deep/foundation"))

# ================================================================ 5. JOURNALS
jr = [(txt(r, "Journal"), int(r["studies"])) for r in JL if r.get("studies")]
THRESH = 3
ge2 = sorted([x for x in jr if x[1] >= THRESH], key=lambda x: x[1])
cov = sum(v for _, v in ge2)
n_ge2 = sum(1 for x in jr if x[1] >= 2)
cov_ge2 = sum(v for _, v in jr if v >= 2)
ABB = {"Remote Sensing Applications: Society and Environment": "RSASE",
       "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing":
           "IEEE JSTARS",
       "International Journal of Applied Earth Observation and Geoinformation":
           "Int. J. Appl. Earth Obs. Geoinf.",
       "ISPRS Journal of Photogrammetry and Remote Sensing": "ISPRS J. Photogramm.",
       "Science of the Total Environment": "Sci. Total Environ.",
       "Remote Sensing of Environment": "Remote Sens. Environ.",
       "Environmental Research: Food Systems": "Environ. Res.: Food Syst.",
       "Scientific Reports": "Sci. Rep.",
       "Remote Sensing": "Remote Sens."}
lab = [(ABB.get(j, j), v) for j, v in ge2]
(HERE / "fig-journals.tex").write_text(BANNER + r"""
\begin{figure}[pos=!t]
\centering
\begin{tikzpicture}
\begin{axis}[
  jsxbar,
  scale only axis, width=3.6cm, height=%0.1fcm,   %%%% labels ~4.2 cm + plot 3.6 cm fits the 8.37 cm column
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,5,10,15,20},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
  bar width=6pt,
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
]
\addplot[draw=none, fill=jsBlue] coordinates {%s};
\end{axis}
\end{tikzpicture}
\caption{Publication venues contributing three or more of the reviewed studies.
These %d venues account for %d of the %d studies. A further %d venues contribute
two studies each; the remaining %d studies appear in venues contributing one each.
RSASE: \emph{Remote Sensing Applications: Society and Environment}.}
\label{fig:journals}
\end{figure}
""" % ((0.46 * len(lab) + 0.3, max(v for _, v in lab) + 4) + axislabels(lab)
       + (len(lab), cov, N, n_ge2 - len(lab), N - cov_ge2)))
notes.append(("Journals", f"{n_ge2} venues with >=2 studies covering {cov_ge2} of {N}; "
              f"{len(ge2)} with >=3 covering {cov}",
              "fig-journals previously said 12 venues covering 65"))
macros["nVenuesGeTwo"], macros["nVenueCoverage"] = n_ge2, cov_ge2
macros["nVenuesSingleCoverage"] = N - cov_ge2

# ================================================================ 6. RESOLUTION + PLATFORM
res = by(EO, "Resolution")
plat = by(EO, "Platform")
n_eo = len({r["study_id"] for r in EO})
RORD = ["Very high (<1 m)", "High (1-10 m)", "Moderate (10-100 m)", "Coarse (>100 m)"]
RCOL = ["jsSeqIV", "jsSeqIII", "jsSeqII", "jsSeqI"]
rows = [(k, len(res.get(k, set()))) for k in RORD if res.get(k)]
pl_items = sorted(((k, len(v)) for k, v in plat.items()), key=lambda x: x[1])
(HERE / "fig-resolution.tex").write_text(BANNER + r"""
\begin{figure*}[pos=!t]
\centering
\begin{tikzpicture}
\begin{groupplot}[group style={group size=2 by 1, horizontal sep=25mm}, height=6.0cm]
\nextgroupplot[
  jsxbar, bar width=12pt, enlarge y limits=0.28,
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
  title style={align=center, at={(0.5,1)}, anchor=south, yshift=3pt},
  width=0.40\textwidth,
  title={(a) Spatial resolution class},
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,20,40,60,80},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
]
\addplot[draw=none, fill=jsSeqIII] coordinates {%s};

\nextgroupplot[
  jsxbar, bar width=12pt, enlarge y limits=0.28,
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
  title style={align=center, at={(0.5,1)}, anchor=south, yshift=3pt},
  width=0.36\textwidth,
  title={(b) Acquisition platform},
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,50,100},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
]
\addplot[draw=none, fill=jsTeal] coordinates {%s};
\end{groupplot}
\end{tikzpicture}
\caption{Imagery used across the %d studies recording an EO source.
(a) Resolution classes; studies combining sensors of different resolution appear
more than once. (b) Acquisition platform.}
\label{fig:resolution}
\end{figure*}
""" % ((int(max(v for _, v in rows) * 1.15),) + axislabels(list(reversed(rows)))
       + (int(max(v for _, v in pl_items) * 1.12),) + axislabels(pl_items) + (n_eo,)))
notes.append(("Resolution classes",
              "; ".join(f"{k} {v}" for k, v in reversed(rows)) + f" (of {n_eo} with EO data)", ""))
notes.append(("Acquisition platform",
              "; ".join(f"{k} {v}" for k, v in reversed(pl_items)),
              "base for the paper's EO percentages is the 124 satellite studies"))

# ================================================================ 7. SPATIO-TEMPORAL
# Studies that record a date range in "Spatio-temporal". The cell is a range
# ("2000-2022"), a single year, or a list of dates ("2016;2019;2023",
# "1993, 2008, 2023"); the span is last year minus first year.
def span_years(v):
    return [int(y) for y in re.findall(r"(?<!\d)(\d{4})(?!\d)", v)]


def span_bucket(v):
    ys = span_years(v)
    if not ys:
        return None
    d = max(ys) - min(ys)
    return "Single year" if d == 0 else ("Short (1--5 yr)" if d <= 5 else
           ("Medium (6--15 yr)" if d <= 15 else "Long ($>$15 yr)"))


bucket = {}
for i, r in enumerate(SA, 1):
    b = span_bucket(txt(r, "Spatio-temporal"))
    if b:
        bucket[i] = b
    elif txt(r, "Spatio-temporal"):
        sys.exit("Spatio-temporal cell with no year in it: %r" % r["Spatio-temporal"])
SPB = ["Single year", "Short (1--5 yr)", "Medium (6--15 yr)", "Long ($>$15 yr)"]
covered = len(bucket)
macros["nSpanReported"] = covered
notes.append(("Spatio-temporal spans",
              f"{covered} of {N} studies record a date range; " +
              "; ".join(f"{b} {sum(1 for v in bucket.values() if v==b)}" for b in SPB), ""))

# --- fig-spatiotemporal: application -> EO data source -> temporal property.
# Ian Ocholla's Sankey (figures/spatio-temporal_tikz.py, 18 Sep 2026), ported
# so that it reads the same spreadsheet as everything else. Each span-reporting
# study carries unit weight, split equally over the data-source nodes it uses
# (VHR and aerial imagery excluded, see st_families in lookups.json); ribbons
# are coloured by application. The third column is a fixed mapping from data
# source to role (st_properties), not a coded variable, so it only regroups the
# middle column. Drawn at its natural size for the 17.38 cm text width of
# cas-dc: no \resizebox, so the labels keep the document's font size.
ST_APP = ["Urban & settlement", "Crop & yield", "LULC & deforestation",
          "Drought & degradation", "Burned area", "Flood & landslide", "Public health"]
ST_APP_LABEL = {"Urban & settlement": r"Urban expansion\\\& settlements",
                "Crop & yield": r"Crop mapping and\\yield estimation",
                "LULC & deforestation": r"Land use\\land cover",
                "Drought & degradation": r"Drought \&\\degradation",
                "Burned area": "Burned area", "Flood & landslide": r"Flood \&\\landslide",
                "Public health": "Public health"}
ST_APP_COLOUR = dict(zip(ST_APP, ["jsBlue", "jsGreen", "jsAmber", "jsRust", "jsPlum", "jsTeal", "jsGrey"]))
# middle column ordered by property so the second stage does not cross itself
ST_DS = ["Landsat / HLS", "Coarse (>100 m)", "Sentinel-2", "PlanetScope / RapidEye", "SAR", "Weather series"]
ST_DS_LABEL = {"Coarse (>100 m)": r"Coarse ($>$100 m)"}
ST_PROP = ["Multi-decade archive", "High revisit", "All-weather (cloud)", "Weather time-series"]
ST_PROP_LABEL = {"Multi-decade archive": r"Multi-decade\\archive", "High revisit": "High revisit",
                 "All-weather (cloud)": r"All-weather\\(cloud)", "Weather time-series": r"Weather\\time-series"}
st_ids = set(bucket)
_sd = {r["study_id"]: txt(r, "Sub-domain") for r in STUDIES}
st_app = {}
for sid in st_ids:
    if _sd[sid] not in LK["st_applications"]:
        sys.exit("add sub-domain %r to st_applications in lookups.json" % _sd[sid])
    st_app[sid] = LK["st_applications"][_sd[sid]]
st_src = collections.defaultdict(set)      # study -> data-source nodes
st_members = collections.defaultdict(set)  # node -> sensors seen in this subset
for r in EO:
    if r["study_id"] in st_ids:
        fam = LK["st_families"][r["Sensor"]]
        if fam:
            st_src[r["study_id"]].add(fam); st_members[fam].add(r["Sensor"])
for r in WL:
    if r["study_id"] in st_ids:
        st_src[r["study_id"]].add("Weather series")
st_flow = collections.Counter()            # (application, data source) -> weight
for sid, srcs in st_src.items():
    for ds in srcs:
        st_flow[(st_app[sid], ds)] += 1.0 / len(srcs)
st_app_h = {a: sum(v for (x, _), v in st_flow.items() if x == a) for a in ST_APP}
st_ds_h = {d: sum(v for (_, y), v in st_flow.items() if y == d) for d in ST_DS}
st_prop_h = {p: sum(st_ds_h[d] for d in ST_DS if LK["st_properties"][d] == p) for p in ST_PROP}
ST_APP = [a for a in ST_APP if st_app_h[a] > 0]
ST_DS = [d for d in ST_DS if st_ds_h[d] > 0]
ST_PROP = [p for p in ST_PROP if st_prop_h[p] > 0]
macros["nSTDrawn"] = len(st_src)
macros["nSTNoSource"] = covered - len(st_src)
assert abs(sum(st_flow.values()) - len(st_src)) < 1e-9

_H = sum(st_app_h.values())
_GAP = 0.03 * _H                # vertical gap between nodes, in study units
_NODEW = 0.09                   # node width, in column units
_CX = {"app": 0.0, "ds": 2.8, "prop": 5.6}
_XS, _YS = 2.06, 0.145          # cm per column unit / per study; 2.06 puts the picture at 17.3 cm


def _stack(order, h):
    pos, top = {}, _H
    for k in order:
        pos[k] = (top - h[k], top); top -= h[k] + _GAP
    return pos


_apos, _dpos, _ppos = _stack(ST_APP, st_app_h), _stack(ST_DS, st_ds_h), _stack(ST_PROP, st_prop_h)
_X = lambda x: x * _XS
_Y = lambda y: y * _YS
_L = []


def _ribbon(x0, y0a, y0b, x1, y1a, y1b, col):
    x0, x1 = _X(x0), _X(x1); y0a, y0b, y1a, y1b = _Y(y0a), _Y(y0b), _Y(y1a), _Y(y1b); cx = (x0 + x1) / 2
    _L.append(f"\\fill[{col},opacity=0.62,draw=white,line width=0.15pt] "
              f"({x0:.3f},{y0a:.3f}) .. controls ({cx:.3f},{y0a:.3f}) and ({cx:.3f},{y1a:.3f}) .. ({x1:.3f},{y1a:.3f}) -- "
              f"({x1:.3f},{y1b:.3f}) .. controls ({cx:.3f},{y1b:.3f}) and ({cx:.3f},{y0b:.3f}) .. ({x0:.3f},{y0b:.3f}) -- cycle;")


_off_a = {a: _apos[a][1] for a in ST_APP}; _off_d = {d: _dpos[d][1] for d in ST_DS}
for a in ST_APP:                                   # stage 1: application -> data source
    for d in ST_DS:
        w = st_flow.get((a, d), 0)
        if w <= 0:
            continue
        ya = _off_a[a]; _off_a[a] -= w; yb = _off_d[d]; _off_d[d] -= w
        _ribbon(_CX["app"] + _NODEW, ya, ya - w, _CX["ds"], yb, yb - w, ST_APP_COLOUR[a])
_off_d = {d: _dpos[d][1] for d in ST_DS}; _off_p = {p: _ppos[p][1] for p in ST_PROP}
for d in ST_DS:                                    # stage 2: data source -> property
    p = LK["st_properties"][d]
    for a in ST_APP:
        w = st_flow.get((a, d), 0)
        if w <= 0:
            continue
        ya = _off_d[d]; _off_d[d] -= w; yb = _off_p[p]; _off_p[p] -= w
        _ribbon(_CX["ds"] + _NODEW, ya, ya - w, _CX["prop"], yb, yb - w, ST_APP_COLOUR[a])
_LBL = "fill=white, fill opacity=0.85, text opacity=1, inner sep=1.4pt, rounded corners=0.6pt"
for order, pos, x, lbl, side in ((ST_APP, _apos, _CX["app"], ST_APP_LABEL, "left"),
                                 (ST_DS, _dpos, _CX["ds"], ST_DS_LABEL, "right"),
                                 (ST_PROP, _ppos, _CX["prop"], ST_PROP_LABEL, "right")):
    for k in order:
        y0, y1 = pos[k]
        _L.append(f"\\fill[jsRule] ({_X(x):.3f},{_Y(y0):.3f}) rectangle ({_X(x + _NODEW):.3f},{_Y(y1):.3f});")
        text = lbl.get(k, esc(k)); yc = _Y((y0 + y1) / 2)
        if side == "left":
            _L.append(f"\\node[anchor=east, align=right, {_LBL}] at ({_X(x) - 0.12:.3f},{yc:.3f}) {{{text}}};")
        else:
            _L.append(f"\\node[anchor=west, align=left, {_LBL}] at ({_X(x + _NODEW) + 0.12:.3f},{yc:.3f}) {{{text}}};")
_htop = _Y(_H + _GAP * 0.6)
_L.append(f"\\node[anchor=south east, font=\\bfseries] at ({_X(_CX['app'] + _NODEW):.3f},{_htop:.3f}) {{Application}};")
_L.append(f"\\node[anchor=south, font=\\bfseries] at ({_X(_CX['ds'] + _NODEW / 2):.3f},{_htop:.3f}) {{Earth observation data}};")
_L.append(f"\\node[anchor=south west, font=\\bfseries] at ({_X(_CX['prop']):.3f},{_htop:.3f}) {{Temporal property}};")


def _members(node):
    return ", ".join(sorted(st_members[node], key=lambda s: (s != "Sentinel-1", s)))


(HERE / "fig-spatiotemporal.tex").write_text(BANNER + r"""%% Ian Ocholla's Sankey, drawn from the "Spatio-temporal", "Sub-domain",
%% "EO sensors" and "Weather data source" columns; groupings in
%% source/lookups.json (st_applications, st_families, st_properties).
\begin{figure*}[pos=!t]
\centering
\begin{tikzpicture}[font=\footnotesize]
%s
\end{tikzpicture}
\caption{Application, Earth observation data source and temporal property for
\nSTDrawn{} of the \nSpanReported{} studies that report a date range (the rest
use very-high-resolution imagery only, or name no sensor). Ribbon width is
proportional to the number of studies: each study contributes unit weight,
divided equally among the data sources it uses, and ribbons are colored by
application. Very-high-resolution satellite and aerial imagery is excluded
because it supplies spatial detail rather than a temporal signal. SAR comprises
%s; the coarse-resolution series are %s. The temporal property is assigned
per data source rather than extracted from the studies.}
\label{fig:spatio_temporal}
\end{figure*}
""" % ("\n".join(_L), _members("SAR"), _members("Coarse (>100 m)")))
notes.append(("Spatio-temporal Sankey",
              f"{len(st_src)} of {covered} span-reporting studies drawn; applications " +
              "; ".join(f"{a} {st_app_h[a]:.1f}" for a in ST_APP) + " | data " +
              "; ".join(f"{d} {st_ds_h[d]:.1f}" for d in ST_DS), ""))

# ================================================================ other numbers
# the paper's EO percentages use base 124 = studies using SATELLITE imagery
_plat = by(EO, "Platform")
sat = _plat.get("Satellite", set())
airb = _plat.get("UAV", set()) | _plat.get("Manned aircraft", set())
macros["nSatellite"] = len(sat)
macros["nSatelliteOnly"] = len(sat - airb)
macros["nSatelliteAndAirborne"] = len(sat & airb)
macros["nAirborneOnly"] = len(airb - sat)
# sensor type among the satellite studies (the sensor paragraph of the Data section)
_cat = by([r for r in EO if r["Platform"] == "Satellite"], "Category")
macros["nSARStudies"] = len(_cat.get("SAR", set()))
macros["nPassiveMicrowave"] = len(_cat.get("Passive microwave", set()))

gee = by(PL, "Platform")
n_pl = len({r["study_id"] for r in PL})
ndvi = by(IX, "Index")
n_ix = len({r["study_id"] for r in IX})
cty = by(CO, "Country")
n_co = len({r["study_id"] for r in CO})
top3 = sorted(cty.items(), key=lambda x: -len(x[1]))[:3]
sens = by(EO, "Sensor")
landsat = set().union(*[v for k, v in sens.items() if "landsat" in k.lower()])

for k, v in [("nPlatformReporting", n_pl), ("nGEE", len(gee.get("Google Earth Engine", set()))),
             ("nIndexStudies", n_ix), ("nNDVI", len(ndvi.get("NDVI", set()))),
             ("nCountryAttributed", n_co), ("nEOStudies", n_eo),
             ("nSentinelTwo", len(sens.get("Sentinel-2", set()))),
             ("nPlanetScope", len(sens.get("PlanetScope", set()))),
             ("nLandsatAny", len(landsat)),
             ("nTopThreeCountries", sum(len(v) for _, v in top3)),
             ("nCountriesRepresented", len(cty)),
             ("nCountriesLeTwo", sum(1 for v in cty.values() if len(v) <= 2))]:
    macros[k] = v

notes += [
    ("GEE", f"{macros['nGEE']}/{n_pl} = {macros['nGEE']/n_pl*100:.1f}%", "paper 86.4% - matches"),
    ("NDVI", f"{macros['nNDVI']}/{n_ix} = {macros['nNDVI']/n_ix*100:.1f}%", "paper 82.3% - matches"),
    ("Top-3 countries",
     "; ".join(f"{k} {len(v)} ({len(v)/n_co*100:.1f}%)" for k, v in top3) +
     f"; combined {macros['nTopThreeCountries']}/{n_co} = {macros['nTopThreeCountries']/n_co*100:.1f}%",
     "paper says 43.9% (n=54/123) - the COMBINED figure is wrong"),
    ("Sentinel-2",
     f"{macros['nSentinelTwo']}/{len(sat)} satellite studies = "
     f"{macros['nSentinelTwo']/len(sat)*100:.1f}%",
     "paper 46.0% - MATCHES; the base is the 124 satellite studies, not 130"),
    ("Landsat, any",
     f"{macros['nLandsatAny']}/{len(sat)} = {macros['nLandsatAny']/len(sat)*100:.1f}%",
     "paper 37.9% (n=47); data gives 48, so one study differs"),
    ("Satellite / airborne split",
     f"satellite only {len(sat-airb)} ({len(sat-airb)/N*100:.1f}%); "
     f"satellite+airborne {len(sat&airb)} ({len(sat&airb)/N*100:.1f}%); "
     f"airborne only {len(airb-sat)} ({len(airb-sat)/N*100:.1f}%)",
     "paper 85.5% (118/138) / 5.1% / 4.3% - last two MATCH, first is 117 not 118"),
]

# ================================================================ 8. PLATFORMS, COVERAGE, OPEN SCIENCE
_ppc = collections.Counter(r["study_id"] for r in PL)
macros["nSinglePlatform"] = sum(1 for v in _ppc.values() if v == 1)
macros["nMultiPlatform"] = sum(1 for v in _ppc.values() if v > 1)
_mc = collections.Counter(txt(r, "Multi-countries") for r in SA)
macros["nSingleCountry"] = _mc["Single country"]
macros["nMultiCountry"] = _mc["Multiple countries"]
macros["nContinental"] = _mc["Continental"]
macros["nSubRegional"] = N - _mc["Single country"] - _mc["Multiple countries"] - _mc["Continental"]
notes.append(("Geographic extent",
              "; ".join(f"{k} {v}" for k, v in _mc.most_common()),
              "paper L238: 95 / 22 / 9 sub-regional / 12"))
_ws = by(WL, "Source"); _ds = by(DM, "Source")
macros["nWeatherStudies"] = len({r["study_id"] for r in WL})
macros["nCHIRPS"] = len(_ws.get("CHIRPS", set()))
macros["nDEMStudies"] = len({r["study_id"] for r in DM})
macros["nSRTM"] = len(_ds.get("SRTM", set()))
notes.append(("Weather sources", "; ".join(f"{k} {len(v)}" for k, v in sorted(_ws.items(), key=lambda x: -len(x[1]))[:8])
              + f"; {macros['nWeatherStudies']} studies", "paper: CHIRPS 40% of weather-data studies"))
notes.append(("DEM sources", "; ".join(f"{k} {len(v)}" for k, v in sorted(_ds.items(), key=lambda x: -len(x[1]))[:6])
              + f"; {macros['nDEMStudies']} studies", "paper: SRTM 67.5% (27/40)"))
macros["nRepository"] = sum(1 for r in SA if not blank(r["Repository"]))
macros["nDataLink"] = sum(1 for r in SA if not blank(r["Data link"]))
macros["nInteractive"] = sum(1 for r in SA if not blank(r["Interactive platform"]))

# infrastructure figure: (a) platforms, (b) open-science practice, (c) repository type
_plc = sorted(((k, len(v)) for k, v in by(PL, "Platform").items()), key=lambda x: x[1])
_ptype = collections.Counter()
for r in SA:
    if not blank(r["Repository"]):
        h = str(r["Repository"]).strip()
        _ptype[(h, LK["repository_type"].get(h, "mutable"))] += 1
_rep = sorted(_ptype.items(), key=lambda x: x[1])
# a stacked xbar needs every series to give a value for every y coordinate,
# otherwise pgfplots stacks the second series onto the first series' rows
_arch = " ".join("(%d,%s)" % (n if t == "archival" else 0, symkey(h)) for (h, t), n in _rep)
_mut = " ".join("(%d,%s)" % (n if t == "mutable" else 0, symkey(h)) for (h, t), n in _rep)
_open = [("Interactive app", macros["nInteractive"]), ("Data or code repository", macros["nRepository"]),
         ("Data link given", macros["nDataLink"])]
(HERE / "fig-infrastructure.tex").write_text(BANNER + r"""
\begin{figure*}[pos=!t]
\centering
\begin{tikzpicture}
\begin{axis}[
  jsxbar, bar width=6pt, enlarge y limits=0.05,
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
  title style={align=center, at={(0.5,1)}, anchor=south, yshift=3pt},
  width=0.60\textwidth, height=%0.1fcm, title={(a) Computing platform named},
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,20,40,60},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
  yticklabel style={font=\scriptsize},
]
\addplot[draw=none, fill=jsBlue] coordinates {%s};
\end{axis}
\end{tikzpicture}

\vspace{6pt}
\begin{tikzpicture}
\begin{groupplot}[group style={group size=2 by 1, horizontal sep=32mm}, height=5.2cm]
\nextgroupplot[
  jsxbar, bar width=10pt, enlarge y limits=0.35,
  nodes near coords={\pgfmathprintnumber[fixed,precision=0]{\pgfplotspointmeta}},
  title style={align=center, at={(0.5,1)}, anchor=south, yshift=3pt},
  width=0.38\textwidth, title={(b) Open-science practice},
  xlabel={Studies (of %d)}, xmin=0, xmax=%d, xtick={0,10,20,30,40},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
]
\addplot[draw=none, fill=jsTeal] coordinates {%s};
\nextgroupplot[
  jsxbarstack, bar width=6pt, enlarge y limits=0.06,
  title style={align=center, at={(0.5,1)}, anchor=south, yshift=3pt},
  width=0.38\textwidth, title={(c) Repository named, by host},
  xlabel={Studies}, xmin=0, xmax=%d, xtick={0,3,6,9},
  symbolic y coords={%s}, ytick=data, yticklabels={%s},
  yticklabel style={font=\scriptsize},
  legend style={at={(0.98,0.04)}, anchor=south east, font=\scriptsize},
]
\addplot[draw=none, fill=jsGreen] coordinates {%s};
\addlegendentry{archival}
\addplot[draw=none, fill=jsRust] coordinates {%s};
\addlegendentry{mutable host}
\end{groupplot}
\end{tikzpicture}
\caption{Computational infrastructure and openness across the %d reviewed studies.
(a) Computing platforms named by the %d studies that report one; a study naming
several is counted once per platform. (b) Open-science practice as a count of all
%d studies. (c) The %d studies naming a data or code repository, by host, with
archival repositories distinguished from mutable code and data hosts.}
\label{fig:infrastructure}
\end{figure*}
""" % ((0.42 * len(_plc) + 1.8, max(n for _, n in _plc) + 10) + axislabels(_plc)
       + (N, max(n for _, n in _open) + 8) + axislabels(_open)
       + (max(n for _, n in _rep) + 3,
          ",".join(symkey(h) for (h, _), _n in _rep), ",".join("{%s}" % esc(h) for (h, _), _n in _rep),
          _arch, _mut, N, len(_ppc), N, macros["nRepository"])))
notes.append(("Platforms", "; ".join(f"{k} {n}" for k, n in reversed(_plc)) +
              f"; {len(_ppc)} studies name one; single {macros['nSinglePlatform']}, several {macros['nMultiPlatform']}",
              "Ian: 69 / 61 GEE / 57 / 12"))
notes.append(("Open science", f"repository {macros['nRepository']}; data link {macros['nDataLink']}; "
              f"interactive {macros['nInteractive']}", "PNG caption: 25 repositories"))

# ---------------------------------------------------------------- outputs
# Percentages quoted in the prose. Emitted without the % sign; write
# \pctRandomForest\% in the text.
for _k, _num, _den in (("pctRandomForest", "nRandomForest", "nClassical"),
                       ("pctSVM", "nSVM", "nClassical"),
                       ("pctDecisionTree", "nDecisionTree", "nClassical"),
                       ("pctVenueCoverage", "nVenueCoverage", "nStudies"),
                       ("pctPlanetScope", "nPlanetScope", "nSatellite"),
                       ("pctSupervisedOnly", "nSupervisedOnly", "nStudies"),
                       ("pctTopThreeCountries", "nTopThreeCountries", "nCountryAttributed"),
                       ("pctSentinelTwo", "nSentinelTwo", "nSatellite"),
                       ("pctLandsatAny", "nLandsatAny", "nSatellite"),
                       ("pctSatelliteOfEO", "nSatellite", "nEOStudies"),
                       ("pctSAR", "nSARStudies", "nSatellite"),
                       ("pctPassiveMicrowave", "nPassiveMicrowave", "nSatellite"),
                       ("pctPlatformReporting", "nPlatformReporting", "nStudies"),
                       ("pctGEE", "nGEE", "nPlatformReporting"),
                       ("pctGEEofAll", "nGEE", "nStudies"),
                       ("pctSingleCountry", "nSingleCountry", "nStudies"),
                       ("pctMultiCountry", "nMultiCountry", "nStudies"),
                       ("pctSubRegional", "nSubRegional", "nStudies"),
                       ("pctContinental", "nContinental", "nStudies"),
                       ("pctRepository", "nRepository", "nStudies"),
                       ("pctDataLink", "nDataLink", "nStudies"),
                       ("pctSpanReported", "nSpanReported", "nStudies"),
                       ("pctCHIRPS", "nCHIRPS", "nWeatherStudies"),
                       ("pctSRTM", "nSRTM", "nDEMStudies")):
    macros[_k] = "%.1f" % (100 * macros[_num] / macros[_den])

(GEN / "numbers.tex").write_text(
    BANNER + "%% \\input this to use the counts in prose, e.g. \\nStudies\n" +
    "".join("\\newcommand{\\%s}{%s}\n" % (macroname(k), v)
            for k, v in sorted(macros.items())))

md = ["# Numbers derived from the extraction spreadsheet", "",
      f"Source: `figures/source/Reviewed_articles_only.xlsx`, {N} studies.",
      "Regenerate with `python3 figures/build_figures.py`.", "",
      "| Quantity | Value from data | Against the paper |", "|---|---|---|"]
md += [f"| {a} | {b} | {c} |" for a, b, c in notes]
(GEN / "NUMBERS.md").write_text("\n".join(md) + "\n")

print(f"source : {SRC.name}  ({N} studies)")
print("wrote  : fig-yearly, fig-domain, fig-methods, fig-models-year,")
print("         fig-journals, fig-resolution, fig-spatiotemporal, fig-infrastructure")
print("         generated/numbers.tex, generated/NUMBERS.md")

# ================================================================ 9. Choropleth map

#!/usr/bin/env python
# =====================================================================
#  figures/fig-choropleth_tikz.py
#  Generates figures/fig-choropleth.tex -- the Africa studies-per-country
#  classed choropleth (B1), drawn natively in TikZ so the manuscript has
#  no raster figures left.
#
#  Mirrors the LOCKED B1 spec in Excel_analysis/20-06/build_figures.py:
#    * uneven right-open bins  [1,3,6,10,19,25) -> 1-2 / 3-5 / 6-9 / 10-18 / 19-24
#    * ColorBrewer Oranges starting ONE STEP DARKER so the grey zero class
#      clears the palest orange (dE 17.1, not 10.5)
#    * zero = flat neutral grey #e8e8e8, drawn as a separate layer, no hatch
#    * white country boundaries, 0.4pt
#    * y clipped at -36 to drop South Africa's sub-Antarctic Prince Edward Is.
#    * legend lower-left in the Atlantic, order 0 / 1-2 / ... / 19-24
#
#  Reads the AUTHORITATIVE workbook in Excel_analysis/20-06/, NOT the stale
#  copy in claude/ that spatio-temporal_tikz.py uses.
#
#  Regenerate with:  python figures/fig-choropleth_tikz.py
#  Edit THIS SCRIPT, never the emitted coordinates.
# =====================================================================
import os
import pandas as pd
import geopandas as gpd
from shapely.geometry import box

#HERE = os.path.dirname(os.path.abspath(__file__))
#ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "Excel_analysis", "20-06"))
GEO = os.path.join(ROOT, "Africa_Countries.geojson")
#XL = os.path.join(ROOT, "selected_articles_only.xlsx")
OUT = os.path.join(HERE, "fig-choropleth.tex")

# ---- locked B1 spec -------------------------------------------------
BIN_EDGES = [1, 3, 6, 10, 19, 25]
BIN_LABELS = ["1--2", "3--5", "6--9", "10--18", "19--24"]
BIN_COLORS = ["fdae6b", "fd8d3c", "e6550d", "a63603", "7f2704"]
ZERO_FILL = "e8e8e8"
EDGE = "white"
EDGE_W = "0.4pt"
SWATCH_EDGE = "8a8a8a"
YMIN = -36.0  # mainland clip

# ---- drawing knobs (tune here, then regenerate) ---------------------
SCALE = 0.175        # cm per degree -> picture ~15.5 cm wide
SIMPLIFY = 0.030     # degrees; ~0.005 cm at SCALE, below print resolution
MIN_AREA = 0.006     # sq deg; drop slivers that cannot render
LEG_X, LEG_Y = 0.020, 0.060   # axes-fraction anchor (matches bbox_to_anchor)
LEG_SW = 3.50        # swatch width  (degrees)
LEG_SH = 2.80        # swatch height (degrees)
LEG_DY = 4.60        # row pitch     (degrees)
LEG_GAP = 1.40       # swatch -> label gap (degrees)
# Font sizes are relative to the 12pt elsarticle base and are then shrunk by
# the \resizebox (x0.849), so set them LARGER here than you want on the page.
# Keep LEG_DY >= 1.3 x the nominal font size in degrees, i.e.
#     LEG_DY >= 1.3 * pt / (SCALE * 28.35);  \Large (17.28pt) -> 4.53
# or the legend rows collide.
FONT_LBL = r"\sffamily\Large"
FONT_TTL = r"\sffamily\Large"

# ---- data -----------------------------------------------------------
af = gpd.read_file(GEO)
af["geometry"] = af.geometry.buffer(0)  # fix 2 invalid geometries
cl = pd.read_excel(XL, sheet_name="country_long")
cnt = cl.groupby("ISO3")["study_id"].nunique().rename("studies")
af = af.merge(cnt, left_on="ISO_3DIGIT", right_index=True, how="left")
af["studies"] = af["studies"].fillna(0).astype(int)

minx, _, maxx, maxy = af.total_bounds
af["geometry"] = af.geometry.intersection(box(minx - 1, YMIN, maxx + 1, maxy + 1))
af = af[~af.geometry.is_empty].copy()

# ---- punch out enclaves --------------------------------------------
# The source geojson models enclaves as OVERLAP, not as interior rings:
# South Africa's polygon covers Lesotho entirely (no hole). Because the
# zero class is drawn first and the data class second, South Africa (24
# studies, darkest orange) would paint straight over Lesotho (0 studies,
# grey) and the enclave would vanish -- the same defect the matplotlib B1
# has. Subtract any country a polygon fully contains so the enclave
# becomes a genuine hole, rendered with the even-odd rule.
_enc = []
for i, a in af.iterrows():
    inner = af[(af.index != i) & af.geometry.within(a.geometry.buffer(1e-9))]
    if len(inner):
        af.at[i, "geometry"] = a.geometry.difference(inner.geometry.union_all())
        _enc += [(a["NAME"], n) for n in inner["NAME"]]
for outer, inner in _enc:
    print("  enclave: %s punched out of %s" % (inner, outer))

af["geometry"] = af.geometry.simplify(SIMPLIFY, preserve_topology=True)


def bin_of(n):
    if n <= 0:
        return None
    for i in range(len(BIN_EDGES) - 1):
        if BIN_EDGES[i] <= n < BIN_EDGES[i + 1]:
            return i
    return len(BIN_COLORS) - 1


def path(coords):
    pts = " -- ".join("(%.3f,%.3f)" % (x * SCALE, y * SCALE) for x, y in coords)
    return pts + " -- cycle"


dropped = 0
body = []
# zero class FIRST -- categorically outside the sequential ramp
for layer in (0, 1):
    for _, r in af.iterrows():
        if (r["studies"] == 0) != (layer == 0):
            continue
        b = bin_of(r["studies"])
        col = ZERO_FILL if b is None else BIN_COLORS[b]
        g = r.geometry
        parts = list(g.geoms) if g.geom_type == "MultiPolygon" else [g]
        for p in parts:
            if p.is_empty or p.area < MIN_AREA:
                dropped += 1
                continue
            segs = [path(list(p.exterior.coords))]
            segs += [path(list(i.coords)) for i in p.interiors]
            rule = "even odd rule," if len(p.interiors) else ""
            body.append(
                r"\fill[" + rule + "fill=mc" + col + ",draw=" + EDGE
                + ",line width=" + EDGE_W + "] " + " ".join(segs) + ";"
            )

# ---- legend ---------------------------------------------------------
x0 = (minx + LEG_X * (maxx - minx)) * SCALE
y0 = (YMIN + LEG_Y * (maxy - YMIN)) * SCALE
sw, sh = LEG_SW * SCALE, LEG_SH * SCALE
dy, gap = LEG_DY * SCALE, LEG_GAP * SCALE
entries = [(ZERO_FILL, "0")] + list(zip(BIN_COLORS, BIN_LABELS))

leg = []
for i, (col, lab) in enumerate(reversed(entries)):  # bottom-up
    y = y0 + i * dy
    leg.append(
        r"\fill[fill=mc" + col + r",draw=swatchedge,line width=0.3pt] "
        + "(%.3f,%.3f) rectangle (%.3f,%.3f);" % (x0, y, x0 + sw, y + sh)
    )
    leg.append(
        r"\node[anchor=west,font=" + FONT_LBL + ",text=black] at "
        + "(%.3f,%.3f) {%s};" % (x0 + sw + gap, y + sh / 2, lab)
    )
leg.append(
    r"\node[anchor=west,font=" + FONT_TTL + ",text=black] at "
    + "(%.3f,%.3f) {No.\\ of studies};" % (x0, y0 + len(entries) * dy)
)

colors = sorted(set(BIN_COLORS) | {ZERO_FILL})
defs = "\n".join(
    r"\definecolor{mc" + c + "}{HTML}{" + c.upper() + "}" for c in colors
)
defs += "\n" + r"\definecolor{swatchedge}{HTML}{" + SWATCH_EDGE.upper() + "}"

HEAD = r"""% =====================================================================
%  figures/fig-choropleth.tex -- studies per African country (fig:choropleth)
%  Classed choropleth, drawn natively in TikZ.
%  Requires: \usepackage{tikz} and \usepackage{xcolor} (no extra libraries).
%  AUTO-GENERATED by figures/fig-choropleth_tikz.py from
%  Excel_analysis/20-06/Africa_Countries.geojson + selected_articles_only.xlsx.
%  Edit the script and regenerate; do NOT hand-tune the coordinates.
%
%  Bins are right-open: [1,3) = "1-2" ... [19,25) = "19-24".
%  Zero countries are flat grey #E8E8E8, a hue outside the ramp and lighter
%  than every orange, so "nothing looks like nothing".
%  ISLANDS (Cabo Verde, Comoros, Mauritius, Sao Tome, Seychelles) are
%  unreadable specks at this scale -- the named zero-country table in the
%  text is MANDATORY, not decoration.
% =====================================================================
"""

MID = r"""\begin{figure}[htbp]
\centering
\resizebox{0.8\linewidth}{!}{%
\begin{tikzpicture}[font=\sffamily]
% ---- country polygons (zero class drawn first) ----
"""

TAIL = r"""\end{tikzpicture}%
}
\caption[Studies per African country]{Number of studies per African country.
Countries with no studies are shown in grey.}
\label{fig:choropleth}
\end{figure}
"""

tex = (HEAD + defs + "\n" + MID + "\n".join(body)
       + "\n% ---- legend (Atlantic dead-space, lower left) ----\n"
       + "\n".join(leg) + "\n" + TAIL)

with open(OUT, "w", encoding="utf-8") as f:
    f.write(tex)

print("wrote %s" % OUT)
print("  %d filled paths, %d sub-printable slivers dropped" % (len(body), dropped))
print("  size: %.0f KB" % (os.path.getsize(OUT) / 1024.0))

